{
 "title": "DEMO Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SSH Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src_ip" ], "type": "tag" },
      { "params": [ "dst_ip" ], "type": "tag" }
     ],
     "measurement": "ssh",
     "select": [
      [
       { "params": [ "repetitions" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ICMP packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src_ip" ], "type": "tag" },
      { "params": [ "dst_ip" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src_ip" ], "type": "tag" },
      { "params": [ "dst_ip" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "packets_transmitted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src_ip" ], "type": "tag" },
      { "params": [ "dst_ip" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src_ip" ], "type": "tag" },
      { "params": [ "dst_ip" ], "type": "tag" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "packets_received" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src_ip" ], "type": "tag" },
      { "params": [ "dst_ip" ], "type": "tag" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "packets_transmitted" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP Port Scanning",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "src_ip" ], "type": "tag" },
      { "params": [ "dst_ip" ], "type": "tag" }
     ],
     "measurement": "port_scan",
     "select": [
      [
       { "params": [ "repetitions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}